### ISSUE TITLE
Installer detected as ML/PE-A virus by Sophos

### ISSUE THREAD

**Issue by gdalbec** [memtest86plus/windows-installer#5]
Sophos Home is reporting:

Threat cleaned

Application, file or content detected as malicious

Hide Advanced Options
ML/PE-A
C:\Downloads\mt86plus_6.00_USB_Installer.exe

The 6.00b3 file is fine...

**Comment by x86fr** [comment]
Reported to Sophos

**Comment by debrouxl** [comment]
Stupid pro-virus software based on stupid "artificial intelligence" and "deep learning" is stupid.

**Comment by x86fr** [comment]
Fully agree!
